### ISSUE TITLE
Ritual SAN Loss

### ISSUE THREAD

**Issue by ericcberg** [TheLastScrub/delta-green-foundry-vtt-system#141]
There should be two SAN losses for a ritual, the SAN lost when learning it and the SAN cost to cast it. Both are automatic, there is no SAN roll to lose a lesser amount, you just roll the dice. (A successful SAN roll when trying to learn a ritual fails to learn it.)

**Comment by TheLastScrub** [comment]
I can add the SAN cost to learn it, I kind of figured the Handler would have that information in the description of the Tome it comes from, but guess it can be here as well. 

The short answer on the high/low SAN cost is the current SAN roll expects two numbers, so it was just easier to leave it that way. However, also from my Handler's Guide, it does seem like there is a success SAN and a failure SAN result:

Page 166/167 of the Handler's Guide:

_Note that Ritual Activation does not depend on the Unnatural skill. The Unnatural skill is useful in finding and identifying effective rituals and studying unnatural entities; but once you’ve learned a ritual, activating it depends on your readiness to break with reality._

_SUCCESS: If the Ritual Activation roll succeeds, the the ritual takes effect and operator pays the costs as
defined by the ritual or the object._

_FAILURE: If the Ritual Activation roll fails, the operator has a choice. Either no effect occurs, **but the operator still must pay half the cost and lose a reduced amount of SAN** (see RITUAL DETAILS on page 168); or
kind of penalty could affect a roll to master a ritual that takes only a few hours to learn, but only if the Handler thinks it’s appropriate._
