### ISSUE TITLE
[FR] Merge FR localisation not applied in Foundry

### ISSUE THREAD

**Issue by Hrunh** [TheLastScrub/delta-green-foundry-vtt-system#161]
Hello @TheLastScrub,
The last merge with correction for French language was not applied in Foundry while it is ok in the direct file.
Could you please look at it?

**Comment by TheLastScrub** [comment]
I just have not had a chance to put together a new package, hopefully I will have a little time to do that this weekend. I've got an infant son now though, so time has been a bit hard to find recently.

**Comment by Hrunh** [comment]
Oh congratulation mate !!!
Ok understood enjoy your moment and take your time :)

**Comment by TheLastScrub** [comment]
Your changes should be in v1.4.9 which I just published, let me know if you still don't see them. Thanks for the localization work.
